spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mysql://ring-project-rds-mysql.chgkg6km2h80.ap-northeast-2.rds.amazonaws.com:3306/ringdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: ringringring
  jpa:
    properties:
      hibernate:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com 
    port: 587
    username: ringringringproject@gmail.com
    password: vbou tyzq pbna txol
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
      
    
    
server:
  port: 9090
  
  
  

     
    
